#define NANO_ID 0 //it's 0 for testing purposes. CHANGE AFTERWARDS
#define FEEDBACK_PWM_MIN 493
#define FEEDBACK_PWM_MAX 1484
#define FEEDBACK_PWM_MIDDLE ( (FEEDBACK_PWM_MAX + FEEDBACK_PWM_MIN) / 2 )
#define COMMAND_PWM_MIN 479
#define COMMAND_PWM_MAX 1473

#define CLOCKWISE_PWM_MIN 2080
#define CLOCKWISE_PWM_MAX 2170
#define CLOCKWISE_SPEED_MIN 64  //unit: 0.1degree/50ms
#define CLOCKWISE_SPEED_MAX 130
#define ANTICLOCKWISE_PWM_MIN 1870  //pwm command that will produce mininum anticlockwise speed
#define ANTICLOCKWISE_PWM_MAX 1780
#define ANTICLOCKWISE_SPEED_MIN -65
#define ANTICLOCKWISE_SPEED_MAX -131