#define NANO_ID 0 //it's 0 for testing purposes. CHANGE AFTERWARDS
#define FEEDBACK_PWM_MIN 493
#define FEEDBACK_PWM_MAX 1484
#define FEEDBACK_PWM_MIDDLE ( (FEEDBACK_PWM_MAX + FEEDBACK_PWM_MIN) / 2 )
#define COMMAND_PWM_MIN 479
#define COMMAND_PWM_MAX 1473

#define CLOCKWISE_PWM_MIN 2120
#define CLOCKWISE_PWM_MAX 2170
#define CLOCKWISE_SPEED_MIN 130
#define CLOCKWISE_SPEED_MAX 283
#define ANTICLOCKWISE_PWM_MIN 1865
#define ANTICLOCKWISE_PWM_MAX 1815
#define ANTICLOCKWISE_SPEED_MIN -133
#define ANTICLOCKWISE_SPEED_MAX -281