#define NANO_ID 0 //it's 0 for testing purposes. CHANGE AFTERWARDS
#define FEEDBACK_PWM_MIN 493
#define FEEDBACK_PWM_MAX 1484
#define FEEDBACK_PWM_MIDDLE ( (FEEDBACK_PWM_MAX + FEEDBACK_PWM_MIN) / 2 )
#define COMMAND_PWM_MIN 479
#define COMMAND_PWM_MAX 1473

#define CLOCKWISE_PWM_MIN 2077
#define CLOCKWISE_PWM_MAX 2164
#define CLOCKWISE_SPEED_MIN 67  //unit: 0.1degree/50ms
#define CLOCKWISE_SPEED_MAX 127
#define ANTICLOCKWISE_PWM_MIN 1871  //this pwm command will produce mininum anticlockwise speed
#define ANTICLOCKWISE_PWM_MAX 1784
#define ANTICLOCKWISE_SPEED_MIN -68
#define ANTICLOCKWISE_SPEED_MAX -127