#define NANO_ID 1 //it's 1 for testing purposes. CHANGE AFTERWARDS
#define FEEDBACK_PWM_MIN 502
#define FEEDBACK_PWM_MAX 1505
#define FEEDBACK_PWM_MIDDLE ( (FEEDBACK_PWM_MAX + FEEDBACK_PWM_MIN) / 2 )
#define COMMAND_PWM_MIN 488
#define COMMAND_PWM_MAX 1493

#define CLOCKWISE_PWM_MIN 2100
#define CLOCKWISE_PWM_MAX 2190
#define CLOCKWISE_SPEED_MIN 65  //unit: 0.1degree/50ms
#define CLOCKWISE_SPEED_MAX 136
#define ANTICLOCKWISE_PWM_MIN 1895  //pwm command that will produce mininum anticlockwise speed
#define ANTICLOCKWISE_PWM_MAX 1800
#define ANTICLOCKWISE_SPEED_MIN -65
#define ANTICLOCKWISE_SPEED_MAX -136