#define NANO_ID 6
#define FEEDBACK_PWM_MIN 499
#define FEEDBACK_PWM_MAX 1504
#define FEEDBACK_PWM_MIDDLE ( (FEEDBACK_PWM_MAX + FEEDBACK_PWM_MIN) / 2 )
#define COMMAND_PWM_MIN 485
#define COMMAND_PWM_MAX 1492

#define CLOCKWISE_PWM_MIN 2103
#define CLOCKWISE_PWM_MAX 2191
#define CLOCKWISE_SPEED_MIN 69  //unit: 0.1degree/50ms
#define CLOCKWISE_SPEED_MAX 134
#define ANTICLOCKWISE_PWM_MIN 1893  //this pwm command will produce mininum anticlockwise speed
#define ANTICLOCKWISE_PWM_MAX 1807
#define ANTICLOCKWISE_SPEED_MIN -68
#define ANTICLOCKWISE_SPEED_MAX -131