#define NANO_ID 2
#define FEEDBACK_PWM_MIN 499
#define FEEDBACK_PWM_MAX 1496
#define FEEDBACK_PWM_MIDDLE ( (FEEDBACK_PWM_MAX + FEEDBACK_PWM_MIN) / 2 )
#define COMMAND_PWM_MIN 485
#define COMMAND_PWM_MAX 1484

#define CLOCKWISE_PWM_MIN 2091
#define CLOCKWISE_PWM_MAX 2178
#define CLOCKWISE_SPEED_MIN 66  //unit: 0.1degree/50ms
#define CLOCKWISE_SPEED_MAX 128
#define ANTICLOCKWISE_PWM_MIN 1794  //this pwm command will produce mininum anticlockwise speed
#define ANTICLOCKWISE_PWM_MAX 1882
#define ANTICLOCKWISE_SPEED_MIN -68
#define ANTICLOCKWISE_SPEED_MAX -132