#define NANO_ID 4
#define FEEDBACK_PWM_MIN 504
#define FEEDBACK_PWM_MAX 1509
#define FEEDBACK_PWM_MIDDLE ( (FEEDBACK_PWM_MAX + FEEDBACK_PWM_MIN) / 2 )
#define COMMAND_PWM_MIN 491
#define COMMAND_PWM_MAX 1495

#define CLOCKWISE_PWM_MIN 2107
#define CLOCKWISE_PWM_MAX 2194
#define CLOCKWISE_SPEED_MIN 67  //unit: 0.1degree/50ms
#define CLOCKWISE_SPEED_MAX 130
#define ANTICLOCKWISE_PWM_MIN 1895  //this pwm command will produce mininum anticlockwise speed
#define ANTICLOCKWISE_PWM_MAX 1807
#define ANTICLOCKWISE_SPEED_MIN -69
#define ANTICLOCKWISE_SPEED_MAX -132