#define NANO_ID 1 //it's 1 for testing purposes. CHANGE AFTERWARDS
#define FEEDBACK_PWM_MIN 502
#define FEEDBACK_PWM_MAX 1505
#define FEEDBACK_PWM_MIDDLE ( (FEEDBACK_PWM_MAX + FEEDBACK_PWM_MIN) / 2 )
#define COMMAND_PWM_MIN 488
#define COMMAND_PWM_MAX 1493

#define CLOCKWISE_PWM_MIN 2103
#define CLOCKWISE_PWM_MAX 2191
#define CLOCKWISE_SPEED_MIN 68  //unit: 0.1degree/50ms
#define CLOCKWISE_SPEED_MAX 134
#define ANTICLOCKWISE_PWM_MIN 1893  //this pwm command will produce mininum anticlockwise speed
#define ANTICLOCKWISE_PWM_MAX 1806
#define ANTICLOCKWISE_SPEED_MIN -70
#define ANTICLOCKWISE_SPEED_MAX -133