#define NANO_ID 1
#define FEEDBACK_PWM_MIN 500
#define FEEDBACK_PWM_MAX 1500
#define FEEDBACK_PWM_MIDDLE ( (FEEDBACK_PWM_MAX + FEEDBACK_PWM_MIN) / 2 )
#define COMMAND_PWM_MIN 485
#define COMMAND_PWM_MAX 1488

#define CLOCKWISE_PWM_MIN 2099
#define CLOCKWISE_PWM_MAX 2185
#define CLOCKWISE_SPEED_MIN 67  //unit: 0.1degree/50ms
#define CLOCKWISE_SPEED_MAX 129
#define ANTICLOCKWISE_PWM_MIN 1888  //this pwm command will produce mininum anticlockwise speed
#define ANTICLOCKWISE_PWM_MAX 1800
#define ANTICLOCKWISE_SPEED_MIN -68
#define ANTICLOCKWISE_SPEED_MAX -132