#define NANO_ID 4
#define FEEDBACK_PWM_MIN 498
#define FEEDBACK_PWM_MAX 1504
#define FEEDBACK_PWM_MIDDLE ( (FEEDBACK_PWM_MAX + FEEDBACK_PWM_MIN) / 2 )
#define COMMAND_PWM_MIN 485
#define COMMAND_PWM_MAX 1495

#define CLOCKWISE_PWM_MIN 2111
#define CLOCKWISE_PWM_MAX 2201
#define CLOCKWISE_SPEED_MIN 71  //unit: 0.1degree/50ms
#define CLOCKWISE_SPEED_MAX 134
#define ANTICLOCKWISE_PWM_MIN 1900  //this pwm command will produce mininum anticlockwise speed
#define ANTICLOCKWISE_PWM_MAX 1814
#define ANTICLOCKWISE_SPEED_MIN -71
#define ANTICLOCKWISE_SPEED_MAX -133