function failed_tests = CASPRTestScript
    results = runtests({'JointTest','CableModelIdealTest','CableModelLinearSpringTest',...
        'CableModelPassiveLinearSpringTest','CableModelVSDFlexureLinearTest',...
        'CableModelVSDTorsionSpringTest','BodyModelRigidTest',...
        'SystemModelBodiesTest','SystemModelCablesTest','SystemModelTest',...
        'ModelConfigTest','IDSolverTest','IDObjectiveInfNormTest',...
        'IDObjectiveLinearTest','IDObjectiveQuadraticTest'});
    failed_tests = [results.Failed];
end