runtests({'JointTest','CableModelIdealTest','CableModelLinearSpringTest',...
    'CableModelPassiveLinearSpringTest','CableModelVSDFlexureLinearTest',...
    'CableModelVSDTorsionSpringTest','BodyModelRigidTest',...
    'SystemModelBodiesTest','SystemModelCablesTest','SystemModelTest',...
    'ModelConfigTest','IDSolverTest','IDObjectiveInfNormTest',...
    'IDObjectiveLinearTest','IDObjectiveQuadraticTest'});