function out1 = F_uv_H0_coeffs(in1,in2,in3)
%F_UV_H0_COEFFS
%    OUT1 = F_UV_H0_COEFFS(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    03-Dec-2020 17:10:29

b1 = in1(1,:);
b2 = in1(2,:);
b3 = in1(3,:);
c1 = in3(1,:);
c2 = in3(2,:);
c3 = in3(3,:);
c4 = in3(4,:);
c5 = in3(5,:);
c6 = in3(6,:);
c7 = in3(7,:);
c8 = in3(8,:);
c9 = in3(9,:);
c10 = in3(10,:);
c11 = in3(11,:);
c12 = in3(12,:);
c13 = in3(13,:);
c14 = in3(14,:);
c15 = in3(15,:);
c16 = in3(16,:);
c17 = in3(17,:);
c18 = in3(18,:);
c19 = in3(19,:);
c20 = in3(20,:);
c21 = in3(21,:);
c22 = in3(22,:);
c23 = in3(23,:);
c24 = in3(24,:);
c25 = in3(25,:);
c26 = in3(26,:);
c27 = in3(27,:);
c28 = in3(28,:);
c29 = in3(29,:);
c30 = in3(30,:);
c31 = in3(31,:);
t2 = b1.^2;
t3 = b2.^2;
t4 = b3.^2;
out1 = c31+b1.*c28+b2.*c29+b3.*c30+c22.*t2+c23.*t3+c24.*t4+c1.*t2.^2+c2.*t3.^2+c3.*t4.^2+b1.*b2.*c25+b1.*b3.*c26+b2.*b3.*c27+b1.*c13.*t2+b2.*c14.*t3+b2.*c16.*t2+b1.*c18.*t3+b3.*c15.*t4+b3.*c17.*t2+b1.*c20.*t4+b3.*c19.*t3+b2.*c21.*t4+c10.*t2.*t3+c11.*t2.*t4+c12.*t3.*t4+b1.*b2.*c4.*t2+b1.*b3.*c5.*t2+b1.*b2.*c6.*t3+b2.*b3.*c7.*t3+b1.*b3.*c8.*t4+b2.*b3.*c9.*t4;
