function t_c = G_F_t_coeffs(in1,in2)
%G_F_T_COEFFS
%    T_C = G_F_T_COEFFS(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    04-Dec-2020 10:36:32

f11 = in2(1);
f12 = in2(4);
f13 = in2(7);
f14 = in2(10);
f15 = in2(13);
f16 = in2(16);
f21 = in2(2);
f22 = in2(5);
f23 = in2(8);
f24 = in2(11);
f25 = in2(14);
f26 = in2(17);
f31 = in2(3);
f32 = in2(6);
f33 = in2(9);
f34 = in2(12);
f35 = in2(15);
f36 = in2(18);
g1 = in1(:,1);
g2 = in1(:,2);
g3 = in1(:,3);
g4 = in1(:,4);
t_c = [f11.*g1+f21.*g2+f31.*g3,f12.*g1+f22.*g2+f32.*g3,f13.*g1+f23.*g2+f33.*g3,f14.*g1+f24.*g2+f34.*g3,f15.*g1+f25.*g2+f35.*g3,g4+f16.*g1+f26.*g2+f36.*g3];
