function [u,v] = G_uv(in1,in2,in3)
%G_UV
%    TANS = G_UV(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    10-Dec-2020 15:27:17
u = [];v = [];
A11 = in1(1);
A12 = in1(4);
A21 = in1(2);
A22 = in1(5);
A31 = in1(3);
A32 = in1(6);
B1 = in2(1,:);
B2 = in2(2,:);
B3 = in2(3,:);
P1 = in3(1,:);
P2 = in3(2,:);
P3 = in3(3,:);
t2 = B3-P3;
t3 = B2-P2;
t4 = A31-A32;
t5 = A32-B3;
t6 = B1-P1;
t7 = A11-A12;
t8 = A21-A22;
t9 = A12-B1;
t10 = A22-B2;
tmp_u = [-(t3.*t5-t2.*t10)./(t3.*t4-t2.*t8);-(t2.*t9-t5.*t6)./(t2.*t7-t4.*t6);-(t3.*t9-t6.*t10)./(t3.*t7-t6.*t8)];
u = tmp_u;
[tmp_u,ind] = unique(round(tmp_u,5),'stable');
r_index = (tmp_u <= 1)  & (tmp_u >= 0); 
ind = ind(r_index);
u = round(u(ind),9);
if isempty(u)
    u = [];v = [];
    return;
end
for i = 1:numel(u)
if round(norm(cross((((in1(:,1) - in1(:,2))*u(i) + in1(:,2)) - in2 ), (in3 - in2))),9) ~= 0
    u(i) = NaN;
end
end
u(isnan(u)) = [];

PA = (in1(:,1) - in1(:,2))*u + in1(:,2);
tmp_v = (in3-in2)./(PA-in2);
v = tmp_v;
[tmp_v,ind] = unique(round(tmp_v,5),'stable');
r_index = (tmp_v <= 1)  & (tmp_v >= 0); 
ind = ind(r_index);
v = round(v(ind),9);
if isempty(v)
    u = [];v = [];
    return;
end

